### ISSUE TITLE
Redundancy in summary view on gad8 page (GO MF)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1701]
summary view 

there is a redundant display for gad8, substrate fkh2, (no unique extensions?)

<img width="954" alt="website ticket redundency_filtering?" src="https://user-images.githubusercontent.com/7359272/118121525-87153d00-b3e9-11eb-95dc-dbf492396719.png">

**Comment by kimrutherford** [comment]
I think this is because we don't remove duplicates for annotations with experimental evidence codes.  The three "phosphorylates fkh2" annotations are EXP and IDA.

**Comment by kimrutherford** [comment]
Sorry, please ignore my previous comment.  :-)

I was looking at the detailed view rather than the summary.  The duplicate in the summary is definitely a bug.  It's possibly triggered by having two annotations that are the same except for evidence code.  I'll dig into that.

**Comment by kimrutherford** [comment]
I think I've worked it out.  The EXP annotation has the extension "has_input(SPBC16G5.15c)" and the IDA annotations have the extension "has_direct_input(SPBC16G5.15c)".  So the summarisation code thinks they are different.

The code should be removing duplicates using the displayed relation name rather than the internal relation name.

**Comment by kimrutherford** [comment]
> The code should be removing duplicates using the displayed relation name rather than the internal relation name.

I think I've fixed the summary code to do that.  It works for me on my desktop and should be visible on the main site on Wednesday morning.  I'll check it then.

**Comment by ValWood** [comment]
the problem here is that has_input and has_direct input on MF are really the same thing. GO changed to use  has_input which means has_direct_input for molecular function.

**Comment by kimrutherford** [comment]
> I think I've fixed the summary code to do that. It works for me on my desktop and should be visible on the main site on Wednesday morning. I'll check it then.

This fix is deployed and working on the main site.  Is there anything else we need to do here?

**Comment by ValWood** [comment]
I still see


protein serine/threonine kinase activity
--
&nbsp; | phosphorylates&nbsp;fkh2&nbsp;during&nbsp;cellular response to glucose stimulus
&nbsp; | phosphorylates&nbsp;fkh2

**Comment by kimrutherford** [comment]
Ah, sorry, I didn't see that.  It's a different bug.  I'll work on that.

**Comment by kimrutherford** [comment]
It looks OK for me now.  Has the annotation changed?

![gad8-summary-1](https://user-images.githubusercontent.com/90474/121836727-29e21380-cd28-11eb-8579-2517c1dbce85.png)

**Comment by ValWood** [comment]
They all seem to have has_substrate now....
I'm not sure, but possibly because I have been working on this pathway. .....

**Comment by kimrutherford** [comment]
> This fix is deployed and working on the main site. Is there anything else we need to do here?

It still needs work: https://github.com/pombase/website/issues/1627#issuecomment-872648908

**Comment by ValWood** [comment]
I think we can close this ticket?

**Comment by ValWood** [comment]
rreopen if not
