### ISSUE TITLE
 syntax Chr_II:3040332!C→CG

### ISSUE THREAD

**Issue by ValWood** [pombase/website#260]
FOr seqeunce updates , I copies the authors syntx

Chr_II:3040332!C→CG

but  this appears as "?" (I neglected to consider of the unusual character)

http://pombase2.aska.gen.nz/reference/PMID%3A26615217

Is it possible to resolve this? If not I can go through and change to "->"

**Comment by kimrutherford** [comment]
It looks like it's "?" not "→" in the contig file for the pdc101 annotation.  Could you check that you pasted it OK?

Exciting characters like "→" should be find in the contig files.

**Comment by ValWood** [comment]
whoops fixed.

**Comment by ValWood** [comment]
the → in the contigs comes out on the web pages as a â

do you want me to change?

**Comment by kimrutherford** [comment]
> the → in the contigs comes out on the web pages as a â��

Oh dear.  That should work fine so please leave as is while I fix the bug.

**Comment by mah11** [comment]
Interesting - it's fine on the static page of gene coordinate changes (http://pombase2.bioinformatics.nz/status/gene-coordinate-changes). Go to the bottom of the page to see examples of perfectly rendered → .

**Comment by kimrutherford** [comment]
> Interesting - it's fine on the static page of gene coordinate changes

Ah, thanks.  That may help with pinning it down.

**Comment by kimrutherford** [comment]
Unfortunately the problem seems to be in the BioPerl code we use to parse the contig file.  I don't think it's going to be easy to fix so could you change them to "->"?

**Comment by ValWood** [comment]
ok done and committed.

**Comment by kimrutherford** [comment]
> ok done and committed.

Thanks, I'll check after the next load finishes.

**Comment by kimrutherford** [comment]
> Thanks, I'll check after the next load finishes.

I can't see the changes in the contig files.  Did you forgot to svn commit?

**Comment by ValWood** [comment]
no I committed?

**Comment by ValWood** [comment]
I see


val-woods-mbp:pombe-embl val$ grep '\->' *.contig
chromosome1.contig:FT                   /controlled_curation="term=warning, Chr_I:101871!A->AG;
chromosome1.contig:FT                   /controlled_curation="term=warning, Chr_I:682993!TC->T;
chromosome1.contig:FT                   /controlled_curation="term=warning, Chr_I:1424708!CA->C;
chromosome1.contig:FT                   /controlled_curation="term=warning, Chr_I:1625092!T->TC;
chromosome1.contig:FT                   /controlled_curation="term=warning, Chr_I:2343703!G->GA;
chromosome1.contig:FT                   /controlled_curation="term=warning, Chr_I:2588066!C->CA;
chromosome1.contig:FT                   /controlled_curation="term=warning, Chr_I:2588021!C->CA;
chromosome1.contig:FT                   /controlled_curation="term=warning, Chr_I:3125118!A->AT;
chromosome1.contig:FT                   /controlled_curation="term=warning, Chr_I:3197528!A->AG;
chromosome1.contig:FT                   /controlled_curation="term=warning, Chr_I:3

**Comment by kimrutherford** [comment]
Ah, I think you missed one:
368262TC→T 5368273 G→GT would change AA PPIYGL to

**Comment by ValWood** [comment]
whoops fixed  now... I couldn't grep for the character and this one did not hit my pattern match.
