### ISSUE TITLE
"target of" section

### ISSUE THREAD

**Issue by ValWood** [pombase/website#274]
![target of](https://cloud.githubusercontent.com/assets/7359272/25292928/4c6b84ac-26d0-11e7-8bd6-04d1d95107ea.jpg)

I think we should treat the target  sections like the other page sections and hide the source/reference by default, and therefore hide redundant annotation in the summary view.

**Comment by ValWood** [comment]
Also, as this section is really more about navigation between pages,  for "affected by mutation in"

I think we should
i) only use single allele genotypes
ii) display genes here not genotypes. This will reduce a lot so that above in the default view  you would only see

affected by mutation in cdc13
affected by mutation in cdc18
affected by mutation in cdc2

you can go to the page to see the details, but at this point it will help the user to be able to more quicky see  a concise list all of the  upstream genes

**Comment by kimrutherford** [comment]
> I think we should treat the target sections like the other page sections and hide the source/reference
> by default, and therefore hide redundant annotation in the summary view.

So we should have "Show details ..." and "Show summary ..." for target of?

> display genes here not genotypes.

That makes sense.

**Comment by kimrutherford** [comment]
> display genes here not genotypes

Should we display show just the genes in the summary but show the gene + genotype in the detailed view?

**Comment by ValWood** [comment]
> Should we display show just the genes in the summary but show the gene + genotype in the detailed view?

That would be very nice!

**Comment by kimrutherford** [comment]
I've added a summary view for the target-of section.  Let me know if you'd like it more compact.

> but show the gene + genotype in the detailed view?

Showing the gene in the detailed view seemed like overkill so I haven't for now.  If you hover over the genotype if shows the gene(s).  Let me know what you think.

**Comment by ValWood** [comment]
Great start. Still to do

- [ ] remove  duplication in summary view
![duplication](https://cloud.githubusercontent.com/assets/7359272/25335162/b816ebfe-28e9-11e7-8797-a28cc5e2e811.jpg)

( I guess this will happen as a consequence of the outstanding redundancy ticket, but good to have an e.g to check off in this section)

**Comment by kimrutherford** [comment]
> remove duplication in summary view

Could explain more what you mean?  I can't see any duplicated lines.  Do you want to move the genes onto one line like:

    GO     regulated by    clp1, csk1, mcs2 and mcs6

**Comment by ValWood** [comment]
Sorry only  cdc25 affected, I misread the msc2/6

See 
substrate of cdc25
directly activated by cdc25
substrate of dc25

**Comment by kimrutherford** [comment]
I've fixed the GO redundancy but it's still a bit odd for phenotypes:

![screenshot from 2017-04-25 00-30-48](https://cloud.githubusercontent.com/assets/90474/25337145/c3f12d26-294e-11e7-910e-ec741d6b14de.png)

**Comment by ValWood** [comment]
I think the summary section of target_of would be helped a lot by displaying the product


Then you would see  immediately that most of these are probably APC....

![product](https://cloud.githubusercontent.com/assets/7359272/25361012/c0629e98-2943-11e7-871b-56d1f8d240ee.jpg)

**Comment by ValWood** [comment]
> I've fixed the GO redundancy but it's still a bit odd for phenotypes:

Only because we still show multi allele.

I don't think they are necessary for the purpose of the target of section, because if they are really importantly upstream they will eventually be captured in GO or single allele.

Nobody has asked for them here, but if they do we can reconsider. For now lets keep it simple...

**Comment by kimrutherford** [comment]
> I think the summary section of target_of would be helped a lot by displaying the product

I've added the product.  I added it to the detailed view too, like in P1.  Is that too much?

> Only because we still show multi allele.

I've removed the multi-allele phenotypes.

How does it look now?

**Comment by ValWood** [comment]
great, you can close this we can open new tickets for anything else...
