### ISSUE TITLE
violin plots

### ISSUE THREAD

**Issue by ValWood** [pombase/website#546]
Resurrect these at some point
http://www.pombase.org/gene_expression/SPBC11B10.09

**Comment by ValWood** [comment]
Mark did these, they are quite cool, presumably the code is somewhere....

**Comment by Antonialock** [comment]
Jurgs group missed these!

**Comment by ValWood** [comment]
removed future, we should try to get these back....
first task is to track down the code...

**Comment by kimrutherford** [comment]
Note to self: might be able to use D3 http://bl.ocks.org/asielen/1a5e8d77ae8feb464167

**Comment by ValWood** [comment]
look promising!

**Comment by ValWood** [comment]
actually I'm not sure that this does the same...
The old plot showed more .... the width of the plot is important...

![violin](https://user-images.githubusercontent.com/7359272/37059675-f44300b4-2185-11e8-9733-bcbcfaacba71.jpg)

**Comment by kimrutherford** [comment]
The page I linked to shows a bunch of different plot types.  There's a "violin plot" button that looks good.  Is that what you tried?

**Comment by ValWood** [comment]
no I didn't... that looks like what we need !

**Comment by kimrutherford** [comment]
From your screenshot it looks like the columns are:

 - G1 protein
 - S protein
 - G2 protein
 - M protein
 - Veg protein
 - Quiescence protein
 - Quiescence RNA
 - Vegetative protein
 - Vegetative RNA

which makes sense except: is "Veg" different to "Vegetative"?

**Comment by ValWood** [comment]
asked Jurg and Sam

**Comment by ValWood** [comment]
Oh I see it's different labs datasets. The other one is Carpy (from legend). It would be better to label both phase and lab....

**Comment by ValWood** [comment]
te st @j.bahler@ucl.ac.uk

**Comment by kimrutherford** [comment]
Just to check: are the red dots the values for the current gene?

For viewing the plots, would it be OK to have a link or button in the "Quantitative gene expression" section that could show/hide the plot.  That's less work than making a separate page.

Are you happy with the order of the datasets?

I've been having a play around with creating plots and I've got this far:
![small](https://user-images.githubusercontent.com/90474/115193046-bfee2900-a13f-11eb-803e-8cfc35dffe75.png)

**Comment by kimrutherford** [comment]
I don't know if this would be useful, but it wouldn't be too much extra work to plot the result from the query builder on top of the violin plot.  Here are the 15 genes annotated with "meiotic cell cycle phase transition":

![small](https://user-images.githubusercontent.com/90474/115196183-bff02800-a143-11eb-9ed5-cea73a4d58cd.png)

**Comment by ValWood** [comment]
- Yes, the red dots are the current gene or RNA
- I think it would be super useful to overlay query results too
- I think the order is probably  OK- but I can't see the labels so I'm not completely sure. 

@juanmatacambridge 
@bahler

**Comment by kimrutherford** [comment]
> For viewing the plots, would it be OK to have a link or button in the "Quantitative gene expression" section that could show/hide the plot. 

I have a proof of principle running on my desktop.  This screenshot is from ssr4 / SPBP23A10.05.


![gene-ex-inline-1](https://user-images.githubusercontent.com/90474/115350809-ac0ef980-a209-11eb-8382-5bb532e2e8b7.png)

**Comment by ValWood** [comment]
I can't remember how to view your desktop ;)

**Comment by ValWood** [comment]
got it!

**Comment by ValWood** [comment]
Can we:
- Make the numbers on the y axis larger.
- Make the dots more prominent (red?)...perhaps smaller too (thinking ahead to if we can overlay query builder results- the dots will need to be small.
- The colour of the background and the violins might be a bit too strong.  If they are all made a little paler it might be helpful.
- For the datasets can we begin with the data type, and put the author in brackets at the end of the string:
Protein, G1 phase (Carpy)

- Would it be better to split the plot into 2 side by side panels and label one 'protein ' and one 'RNA' rather than include the data types in the labels?

Do we know what these plots looked like before for comparison?

**Comment by kimrutherford** [comment]
> Make the numbers on the y axis larger.

I've done that.

> Make the dots more prominent (red?)

I've done that.

> perhaps smaller too (thinking ahead to if we can overlay query builder results- the dots will need to be small.

I was thinking that we'd use smaller dots if there are more of them.

> The colour of the background and the violins might be a bit too strong. If they are all made a little paler it might be helpful.

I've made them paler.

> For the datasets can we begin with the data type, and put the author in brackets at the end of the string:
> Protein, G1 phase (Carpy)

That will probably be too long in this case:
Protein G1 quiescence (Marguerat)

but would be OK if split over two lines:
```
Protein G1 quiescence
     (Marguerat)
```

> Would it be better to split the plot into 2 side by side panels and label one 'protein ' and one 'RNA' rather than include the data types in the labels?

That might help.  I'll try to do that tomorrow so we can see how it looks.

> Do we know what these plots looked like before for comparison?

Do you mean in Ensembl times?  I've been using this screenshot as a guide: https://github.com/pombase/website/issues/546#issuecomment-370936279


https://github.com/pombase/website/issues/546#issuecomment-370936279

**Comment by ValWood** [comment]
> I was thinking that we'd use smaller dots if there are more of them.
size fine in that case

> but would be OK if split over two lines:
2 lines is fine, It just seems that  what it is should be the first thing

> Do you mean in Ensembl times? I've been using this screenshot as a guide:
I prefer the simpler colours here.  A different colour for protein vs RNA is useful, but for the phases people will need to read the labels anyway so I'm not sure that it helps to have a different colour for each phase.

Any other opinions on this?

I like the little icon you added to indicate the plots too.

**Comment by bahler** [comment]
Looks good! What is the bright blue circle in the violin plots?

Cheers,
-Jürg

**Comment by ValWood** [comment]
The protein/gene for the specific gene page- In the updated version this will be red.

**Comment by bahler** [comment]
Cool!

**Comment by mah11** [comment]
This does look cool :) I like the query result plotting a lot.

If the dot is going to be red, don't forget to check it for color-blind compatibility.

**Comment by kimrutherford** [comment]
I've changed the colours to pale grey with a red dot.

> If the dot is going to be red, don't forget to check it for color-blind compatibility.

Just checked and it's OK at the moment.

**Comment by kimrutherford** [comment]
> it wouldn't be too much extra work to plot the result from the query builder on top of the violin plot. 

Rather than adding an button (there are too many already), I was thinking we could turn the Visualise button into a little drop down menu.  Would that be OK?

![gene-ex-query-builder-1](https://user-images.githubusercontent.com/90474/115480643-0a39ec00-a29f-11eb-8b0a-e29f27ddd0ce.png)

**Comment by kimrutherford** [comment]
> Would it be better to split the plot into 2 side by side panels and label one 'protein ' and one 'RNA' rather than include the data types in the labels?

How's this?:

![out](https://user-images.githubusercontent.com/90474/115481129-02c71280-a2a0-11eb-9b08-37b4f87807fd.png)

**Comment by kimrutherford** [comment]
> it wouldn't be too much extra work to plot the result from the query builder on top of the violin plot.

That's implemented now.  You can try it on my desktop version:
https://desktop.kmr.nz/gene-ex/from/id/ffc2b9d5-6103-4de0-8c7d-0a74ed574ca2

The data table used to make the plots is here:
https://www.pombase.org/nightly_update/misc/gene_expression_table.tsv

Maybe we should put a copy in a more public place?

**Comment by ValWood** [comment]
> Rather than adding an button (there are too many already), I was thinking we could turn the Visualise button into a little drop down menu. Would that be OK?
+1, I envisioned it under this menu

>How's this?:
I like the split and the simpler colours

>That's implemented now. You can try it on my desktop version:
Works well

Q Moon on a stick- is it possible to tell you which genes when you mouseover? It is interesting to see the protein levels, but mainly they are the same through the cell cycle, it would be much more useful if you could   tell which individuals had changed.

Q Should we still show the graph on gene pages if there is no data, as for protein in this case?
https://desktop.kmr.nz/gene/SPBC651.03c

Q  Following from these 2 Q, should  we provide a list of  genes/proteins for which no data is available in  the composite  query builder plot?

**Comment by bahler** [comment]
I like the separation of protein and mRNA graphs.

Cheers,
-Jürg

**Comment by mah11** [comment]
> The data table used to make the plots is here:
> https://www.pombase.org/nightly_update/misc/gene_expression_table.tsv
> 
> Maybe we should put a copy in a more public place?

I can add an entry-with-link to the "Annotation datasets" table on the [datasets](https://www.pombase.org/datasets) page.

I suggest directly in https://www.pombase.org/data/ for the location, but I'm not that fussed - just let me know where to link to.

**Comment by kimrutherford** [comment]
> Q Moon on a stick- is it possible to tell you which genes when you mouseover? It is interesting to see the protein levels, but mainly they are the same through the cell cycle, it would be much more useful if you could tell which individuals had changed.

I don't know of a way to do that without a re-working of the implementation.  Currently the graphing code just returns a .png to the browser.  Mouse overs might have to be a longer term plan.

> Should we still show the graph on gene pages if there is no data, as for protein in this case?

I'd vote for keeping graphs with no data, for consistency.

**Comment by kimrutherford** [comment]
Things we need to remember to document:
  - we can only display violin plots for genes list up to 150 long
  - we only show the Carpy and Marguerat datasets
  - need a sentence before the plot on the gene page and before the query builder image

**Comment by kimrutherford** [comment]
As a placeholder, I've added sentences like this above the violin plots on the gene pages:
```
These are "violin plots" of the available gene expression datasets with the expression level
of wee1 (if available) shown as a red point:
```

And this on the gene results pages:
```
These are "violin plots" of the available gene expression datasets with the expression levels
of the genes shown as a red points:
```

Let me know what edits you'd like.

**Comment by bahler** [comment]
Hi Kim,

These descriptions are clear. I just suggest to shorten a bit:

"Violin plots" of available gene expression datasets with expression level
of wee1 (if available) shown as red point:

"Violin plots" of available gene expression datasets with gene-expression levels
shown as red points:


Cheers,
-Jürg

**Comment by kimrutherford** [comment]
Thanks Jürg.  I've made those changes and they'll be visible in the morning.

**Comment by mah11** [comment]
Are the violin plots meant to be switched off at the moment? On gene pages the "View gene expression plots" message shows (with its cool graphic), but I get the broken-image icon when I click it. In advanced search results, the Visualise menu has "Gene expression (disabled)" in grey in Firefox or Chrome; Safari on a Mac attempts the visualization but generates the broken-image icon in a big box.

I was about to do the documentation ...

**Comment by kimrutherford** [comment]
Sorry about that!  It's fixed now and I promise not to break it again.

**Comment by mah11** [comment]
Thanks! :)

**Comment by mah11** [comment]
Sorry for bad news, but the "visualise" search results part of the bug is still there (still says "disabled"). I even did shift-refresh and a new search.

**Comment by mah11** [comment]
oops, duh, yes. Maybe we should include a message about that, since even I can't remember the limit from day to day :P

How about "Gene expression (up to 150 genes)" for the grey text ... or even in all cases?

**Comment by kimrutherford** [comment]
> How about "Gene expression (up to 150 genes)" for the grey text ... or even in all cases?

Yep that makes sense.  I'll change that.

**Comment by kimrutherford** [comment]
> How about "Gene expression (up to 150 genes)" for the grey text ... or even in all cases?

That's live now.

**Comment by kimrutherford** [comment]
I'll close this.  We can open new issues for bugs and tweaks.

**Comment by ValWood** [comment]
@mah11  to announce, should we have a news item?

**Comment by mah11** [comment]
> should we have a news item?

Is this a request to create a news item? I have no preference whether there is one or not (it's been live for a month and a half ... doesn't feel that newsy any more :P ... but maybe users haven't spotted it).

**Comment by ValWood** [comment]
I think it would be useful to announce in some way, so we can pretend it is new.
Especially the feature in the Advanced search to see your gene list on a plot, which I doubt many people have seen.

**Comment by ValWood** [comment]
could be a pombelist post instead? Or both?

**Comment by bahler** [comment]
Yes, that is a helpful feature which people would not easily stumble upon.

Cheers,
-Jürg

**Comment by mah11** [comment]
> could be a pombelist post instead? Or both?

Which -- either or both -- do you want?

**Comment by ValWood** [comment]
Both please.
