### ISSUE TITLE
possible bug in query builder

### ISSUE THREAD

**Issue by ValWood** [pombase/website#848]
alerted by
https://github.com/pombase/website/issues/842#issuecomment-403725211

for some reason, when I use  canned query for inviable genes

1367 | inviable vegetative cell population (FYPO:0002061) [Null expression - single allele genotypes]

as input ckb1 is green (viable) but, its
Gene Deletion Viability: Viable

**Comment by ValWood** [comment]
We did "deletions" because sometimes the disruptions are  leave a substantial fragment of the 
gene product.

I think it's probably OK to do it differently in the query builder, but it should be clear the difference.

I think we could use "deletion" only for  viability phenotype because everything should have one, even if it has disru[tion too.

Thoughts? @mah11 @Antonialock

**Comment by ValWood** [comment]
Need to discuss on  next call, any input before then would be useful

**Comment by Antonialock** [comment]
In principle it could have been useful to make a distinction (as you point out some disruptions are incomplete)

in practice I think the distinction could be a bit meaningless - many papers only state "yfg1delta", and they might send you on a paperchase to find out if the gene was disrupted or 'deleted' - so many alleles marked as deletions could be 'anything' really.

**Comment by ValWood** [comment]
That is true. If the author calls it a deletion we call it a deletion...but sometimes a deletion is a "disruption" and not a deletion and we know there is residual activity.
"disruption" gives us an opportunity to move things out of the deletion category once we know this (and that the incomplete diruption has a different effect)..

For this reason, I favour exclusion of disruption (because at least, for the deletion project these were all checked). The deletion vs disruption accounts for some of the published differences.

 We can then live with the fact that some  mutant alleles described as deletion may be partial, but if we find that is true, and  results in a different phenotype  we can reassign as a disruption.

If the phenotypes are differnet between a deletion project construc and an existing "deletion" it is likely that these will, at come point be checked, which will allow us to resolve.

**Comment by ValWood** [comment]
ACTION MAke the  gene page summary of viability mirror the Query builder query for viability

**Comment by kimrutherford** [comment]
> Make the gene page summary of viability mirror the Query builder query for viability

I think I've made the fix in time to tonight's update.  I'll check when it's done.

**Comment by kimrutherford** [comment]
Looks like it worked.  ckb1 is now has "Gene Deletion Viability: Depends on conditions"

**Comment by ValWood** [comment]
Great!

**Comment by kimrutherford** [comment]
I think this is fixed.  Please reopen if I've misunderstood.

**Comment by ValWood** [comment]
I can't remember if I tested. Will re-open and double check...should get to it later....

**Comment by ValWood** [comment]
We still have a difference between the query builder and the  gene pages

ckb1 is inviable according to the query builder
but the deletion is "viable"

only the disruption is "inviable" (at low temperature)
but it is reported as "Gene Deletion Viability: Depends on conditions"

what do we need to do to make the same based on above?
@mah11  can you tell us? 
It seems confusing the way it is right now?

Introduce a "conditional category" to the search?

**Comment by ValWood** [comment]
one thing

the query is described as "inviable deletions"

but actually returns

1368 | inviable vegetative cell population (FYPO:0002061) [Null expression - single allele genotypes]

which is inviable deletions or disruptions, all conditions, should be clearer if kept like this.

**Comment by ValWood** [comment]
OK, it's probably OK as it is.

ckb1 appears in both lists, viable and inviable
and has
Gene Deletion Viability: Depends on conditions

which is fine.

Just need to be clear in the query buider if we use disruptions.
Description does not currently make this clear:
the query is described as "inviable deletions"

@mah11 ?

**Comment by mah11** [comment]
The search details indicate that it counts everything with null expression (i.e. deletions and null-exp disruptions). For ckb1 it's the disruption that has viable at standard temperature and inviable at low temp.

So we could just edit the description to something more informative - would "viable|inviable deletions and disruptions" be enough?

**Comment by ValWood** [comment]
Yes that'll will do it. I think that it is the solution I was trying to articulate!

**Comment by kimrutherford** [comment]
> would "viable|inviable deletions and disruptions" be enough?

So do we just need to change the text in the "Commonly used queries" section?

**Comment by ValWood** [comment]
That's correct.

**Comment by kimrutherford** [comment]
OK, done!
