### ISSUE TITLE
GAF downloads (from advanced search etc)

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#949]
(Moved from #576)

We'd like an option to download GAF data: http://www.geneontology.org/page/go-annotation-file-gaf-format-21

Is the idea that you would get a GAF file containing the annotations for just the genes in the query results?  Or do we want things like being able to download the annotations from a GO table on a gene page?  Or download all the annotations on a GO term page?

**Comment by mah11** [comment]
IIRC, the original idea was annotations for query result genes. But I could imagine the other scenarios being useful on occasion (and making us look cool and clever).

**Comment by ValWood** [comment]
Yep, I can't see an immediate use case for GO terms on a gene page, but who knows, and I'm sure all the others would have some applications (phenotypes on a gene page might be wanted, for example, because the lists are much longer)

**Comment by kimrutherford** [comment]
OK, I'll aim to get the GAF download from the gene results working first.  We can add other options as needed.

**Comment by ValWood** [comment]
not urgent anyway....

**Comment by ValWood** [comment]
in addition to getting all the terms, just the most specific terms as displayed in the summary view
https://github.com/pombase/website/issues/1026

**Comment by mah11** [comment]
the #1026 part doesn't fit the description "GAF download"

**Comment by ValWood** [comment]
It needs discussion and its work in the same area and will be completed at the same time.
(it's the same functionality, essentially).

**Comment by kimrutherford** [comment]
I've had a first attempt at this and it's live in the dev server.  It's still a work in progress as it's too slow.  It's fine for up to maybe 500 genes or maybe 1000 if you select just one aspect.  I'll dig into things tomorrow to find out what the problem is.

![gaf-download-1](https://user-images.githubusercontent.com/90474/90393818-962ebf00-e0e5-11ea-8177-419a3f95b85f.png)

**Comment by mah11** [comment]
good to see this getting started - cheers!

**Comment by kimrutherford** [comment]
> It's still a work in progress as it's too slow.

It's much faster now so I think it's ready for testing.

> good to see this getting started - cheers!

Thanks!

**Comment by mah11** [comment]
> I think it's ready for testing.

Cool! I'll give it a spin soon.

**Comment by mah11** [comment]
Looks good! There are a few differences between downloaded lines and GAF-sent-to-GO lines, but they seem to fall into one of two categories:

- synonym order differences
- 'binds' vs. 'with' as described in the [long comment](https://github.com/pombase/pombase-chado/issues/744#issuecomment-675251087) on #744

**Comment by kimrutherford** [comment]
Great, thanks for testing.

**Comment by kimrutherford** [comment]
I've done some testing today and this seems to work well.  When should we plan to release it on the main site?

**Comment by ValWood** [comment]
I think we could release this, but 

- [ ] should we  a note somewhere that only direct annotations will be downloaded, not inferred ones?
- [ ] Another suggestion was to  have the ability to only download the leafnod annotation (i.e the summary view annotations)
- [ ] Do we still want to enable download of annotations directly from gene pages?  It was mentioned above. (I'm not fussed for GO, think this might be more  useful for gene pages- also you could emulate this by just supplying  the gene ID in the list upload and downloading the annotations)

**Comment by kimrutherford** [comment]
> should we a note somewhere that only direct annotations will be downloaded, not inferred ones?

Midori has a good FAQ answer about that:
 https://www.pombase.org/faq/why-are-go-terms-missing-downloadable-annotation-file

> Do we still want to enable download of annotations directly from gene pages?

It sounds useful, but I think it should be moved to a separate issue.

**Comment by ValWood** [comment]
moved to a new ticket
https://github.com/pombase/website/issues/1655

**Comment by ValWood** [comment]
So can this one close now?

**Comment by kimrutherford** [comment]
It's not on the main site yet.  We should probably add some documentation before that.

**Comment by mah11** [comment]
I have one more suggestion: drop "Format" from the tab header, so it just says "GO Annotations".

> We should probably add some documentation

It will only take me a few minutes to add a bit of documentation (most of the knotty stuff is done, e.g. the FAQ Kim noted above, and can be linked to). Just shout and I'll most likely give you a same-day turnaround ;)

**Comment by kimrutherford** [comment]
> I have one more suggestion: drop "Format" from the tab header, so it just says "GO Annotations".

I've made that change.

> Just shout and I'll most likely give you a same-day turnaround ;)

Thanks Midori.

If you can add the bit of documentation sometime tomorrow (UK Tuesday) we can release it on Wednesday morning.

**Comment by mah11** [comment]
> If you can add the bit of documentation sometime tomorrow (UK Tuesday)

OK, that's done :)

**Comment by kimrutherford** [comment]
Great, thanks.

I've committed the change that will make it available on the main site.  I'll check in the morning and then close the issue.

**Comment by kimrutherford** [comment]
The load failed because of a problem with a modification data file.  I'll check again on Thursday morning.

**Comment by ValWood** [comment]
Oh poop, I didn't fix date-> 21-01-12. I couldn't do it in Excel because it wanted to do its own thing....will do that now....

**Comment by ValWood** [comment]
Oh I had done that , or somebody else had. Now fixed from 2020->2021...

**Comment by ValWood** [comment]
....and in the phenotype file

**Comment by ValWood** [comment]
I put  taxon:4896 instead of 4896...now fixed...

**Comment by ValWood** [comment]
I re checked the tabbing, but that seems OK too so hopefully I fixed....

**Comment by kimrutherford** [comment]
Thanks for the fixes.  I've removed some blank lines at the end of the file too.

**Comment by kimrutherford** [comment]
I think we can close this.
